require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/queue_schema.rb"

# Documentation not enforced
Style/Documentation:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - "app/admin/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*.rb"
    - "app/views/**/*.arb"

# Allow rescue shorthand in specs
Style/RescueModifier:
  Exclude:
    - "spec/**/*.rb"
