require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/queue_schema.rb"
    - vendor/bundle/**/* # https://github.com/rubocop/rubocop/issues/9832#issuecomment-882111229

# Documentation not enforced
Style/Documentation:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - "app/admin/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*.rb"
    - "app/views/**/*.arb"

# Allow rescue shorthand in specs
Style/RescueModifier:
  Exclude:
    - "spec/**/*.rb"

# Allow policies to have repeated examples and descriptions
RSpec/RepeatedDescription:
  Exclude:
    - "spec/policies/**/*_spec.rb"
RSpec/RepeatedExample:
  Exclude:
    - "spec/policies/**/*_spec.rb"

# Allow policies to have deep nesting
RSpec/NestedGroups:
  Exclude:
    - "spec/policies/**/*_spec.rb"
