services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ticketinghub/api:local
    command: bin/rails server --binding 0.0.0.0
    entrypoint: bin/docker-entrypoint-dev-web
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

  worker:
    image: ticketinghub/api:local
    command: bin/jobs
    entrypoint: bin/docker-entrypoint-dev-worker
    depends_on:
      - db
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

  db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  css:
    image: ticketinghub/api:local
    command: yarn build:app:css --watch
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

  admin_css:
    image: ticketinghub/api:local
    command: yarn build:admin:css --watch
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

  rubocop:
    image: ticketinghub/api:local
    entrypoint: bin/docker-entrypoint-dev-rubocop
    command: bundle exec rubocop --start-server --no-detach
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/app

volumes:
  bundle_cache:
