services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: ${DOCKER_STAGE_TARGET:-dev}
    image: ${DOCKER_IMAGE:-wealth:local}
    command: bin/rails server --binding 0.0.0.0
    entrypoint: bin/docker-entrypoint-dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

  css:
    image: ${DOCKER_IMAGE:-wealth:local}
    command: yarn build:app:css --watch
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

  admin_css:
    image: ${DOCKER_IMAGE:-wealth:local}
    command: yarn build:admin:css --watch
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

  rubocop:
    image: ${DOCKER_IMAGE:-wealth:local}
    entrypoint: bin/docker-entrypoint-dev-rubocop
    command: bundle exec rubocop --start-server --no-detach
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/app

volumes:
  bundle_cache:
