services:
  web:
    build:
      context: .
      target: ${DOCKER_STAGE_TARGET:-dev}
    image: ${DOCKER_IMAGE:-wealth:local}
    command: bin/rails server --binding 0.0.0.0
    entrypoint: bin/docker-web-entrypoint.sh
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

  worker:
    image: ${DOCKER_IMAGE:-wealth:local}
    entrypoint: bin/docker-worker-entrypoint.sh
    command: bundle exec good_job start
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db

  rubocop:
    image: ${DOCKER_IMAGE:-wealth:local}
    entrypoint: bin/docker-rubocop-entrypoint.sh
    command: bundle exec rubocop --start-server --no-detach
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/app

  db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  bundle_cache:
