default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

docker: &docker
  host: db
  username: postgres
  password: postgres

development:
  primary:
    <<: *default
    <<: *docker
    database: wealth_development
  queue:
    <<: *default
    <<: *docker
    database: wealth_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  <<: *docker
  database: wealth_test

production:
  <<: *default
  database: wealth_production
