default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3
  queue:
    <<: *default
    database: db/development_queue.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: db/test.sqlite3
  queue:
    <<: *default
    database: db/test_queue.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: db/production.sqlite3
  queue:
    <<: *default
    database: db/production_queue.sqlite3
    migrations_paths: db/queue_migrate
