default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

docker: &docker
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: postgres
  password: postgres

development:
  primary:
    <<: *default
    <<: *docker
    database: wealth_development
  queue:
    <<: *default
    <<: *docker
    database: wealth_development_queue
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    <<: *docker
    database: wealth_test
  queue:
    <<: *default
    <<: *docker
    database: wealth_test_queue
    migrations_paths: db/queue_migrate

production: &production
  host: <%= ENV["DB_HOST"] %>
  username: wealth
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  primary:
    <<: *default
    <<: *production
    database: wealth_production
  queue:
    <<: *default
    <<: *production
    database: wealth_production_queue
    migrations_paths: db/queue_migrate
