default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

docker: &docker
  host: db
  username: postgres
  password: postgres

development:
  primary:
    <<: *default
    <<: *docker
    database: wealth_development
  queue:
    <<: *default
    <<: *docker
    database: wealth_development_queue
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    <<: *docker
    database: wealth_test
  queue:
    <<: *default
    <<: *docker
    database: wealth_test_queue
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
