service: wealth
image: thisismydesign/wealth

servers:
  web:
    - 157.180.24.197
  worker:
    hosts:
      - 157.180.24.197
    cmd: bin/jobs

proxy:
  ssl: true
  host: wealth.mysoftware.services

registry:
  server: ghcr.io
  username: thisismydesign
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    DB_HOST: 157.180.24.197
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

# Use a persistent storage volume for sqlite database files and local Active Storage files.
volumes:
  - "/mnt/HC_Volume_102174451/wealth:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:16.1-alpine
    host: 157.180.24.197
    port: 5432
    env:
      clear:
        POSTGRES_USER: wealth
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
