service: wealth
image: thisismydesign/wealth

servers:
  web:
    - 157.180.24.197
  worker:
    hosts:
      - 157.180.24.197
    cmd: bin/jobs

proxy:
  ssl: true
  host: wealth.mysoftware.services

registry:
  server: ghcr.io
  username: thisismydesign
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    DB_HOST: wealth-db
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  # db:
  #   image: postgres:16.1-alpine
  #   host: 157.180.24.197
  #   port: "127.0.0.1:5432:5432"
  #   env:
  #     clear:
  #       POSTGRES_USER: wealth
  #     secret:
  #       - POSTGRES_PASSWORD
  #   directories:
  #     - data:/var/lib/postgresql/data

  backup:
    image: eeshugerman/postgres-backup-s3:16
    host: 157.180.24.197
    env:
      clear:
        SCHEDULE: "@daily"
        S3_REGION: "eu-central-1"
        S3_BUCKET: wealth-production
        S3_PREFIX: backups
        POSTGRES_HOST: wealth-db
        POSTGRES_DATABASE: wealth_production
        POSTGRES_USER: wealth
      secret:
        - POSTGRES_PASSWORD
        - S3_ACCESS_KEY_ID
        - S3_SECRET_ACCESS_KEY
