name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/wealth_test

    steps:
      - uses: actions/checkout@v3

      - name: Pull images
        run: docker compose pull db

      - name: Start PostgreSQL with Docker Compose
        run: docker compose up db -d

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Wait for PostgreSQL to be ready
        run: timeout 30s bash -c 'until docker compose exec -T db pg_isready; do sleep 1; done'

      - name: Setup app
        run: bin/rails db:prepare

      - name: Test
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Lint
        run: bundle exec rubocop

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [test, lint]
    if: github.ref == 'refs/heads/master'
    concurrency: deploy

    env:
      DOCKER_BUILDKIT: 1
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run deploy command
        run: bundle exec kamal setup
