name: Release

on:
  push:
    branches:
      - master

env:
  HEROKU_APP_NAME: wealth

concurrency:
  group: ${{ github.ref }}-release

jobs:
  build-and-push-image-to-heroku:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx to be able to use caching
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
          file: Dockerfile
          target: app
          cache-from: type=gha
          cache-to: type=gha

  deploy-production:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-and-push-image-to-heroku]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Run release command
        run: heroku container:release web -a ${{ env.HEROKU_APP_NAME }}
